02/18/2022 17:32:09 INFO - Importing station orders
02/18/2022 17:32:09 INFO - Creating positions

02/18/2022 17:32:15 INFO - Initializing database connection
02/18/2022 17:32:19 INFO - Verbose connection successful. Status code: 200
02/18/2022 17:32:19 INFO - Refreshing units
02/21/2022 16:54:43 INFO - Importing station orders
02/21/2022 16:54:43 INFO - Creating positions

02/21/2022 16:55:12 INFO - Importing station orders
02/21/2022 16:55:12 INFO - Creating positions

02/21/2022 16:57:24 INFO - Importing station orders
02/21/2022 16:57:24 INFO - Creating positions

02/21/2022 16:59:09 INFO - Importing station orders
02/21/2022 16:59:09 INFO - Creating positions

02/21/2022 16:59:19 INFO - Importing station orders
02/21/2022 16:59:19 INFO - Creating positions

02/21/2022 16:59:39 INFO - Importing station orders
02/21/2022 16:59:39 INFO - Creating positions

02/21/2022 16:59:44 INFO - Initializing database connection
02/21/2022 16:59:51 INFO - Verbose connection successful. Status code: 200
02/21/2022 16:59:51 INFO - Refreshing units
02/21/2022 16:59:54 INFO - Initializing database connection
02/21/2022 16:59:58 INFO - Verbose connection successful. Status code: 200
02/21/2022 16:59:58 INFO - Refreshing units
02/21/2022 17:00:33 INFO - Importing station orders
02/21/2022 17:00:33 INFO - Creating positions

02/21/2022 17:01:05 INFO - Importing station orders
02/21/2022 17:01:05 INFO - Creating positions

02/21/2022 17:02:40 INFO - Importing station orders
02/21/2022 17:02:40 INFO - Creating positions

02/21/2022 17:02:47 INFO - Initializing database connection
02/21/2022 17:02:52 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:02:52 INFO - Refreshing units
02/21/2022 17:03:55 INFO - Importing station orders
02/21/2022 17:03:55 INFO - Creating positions

02/21/2022 17:04:00 INFO - Initializing database connection
02/21/2022 17:04:04 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:04:04 INFO - Refreshing units
02/21/2022 17:06:01 INFO - Importing station orders
02/21/2022 17:06:01 INFO - Creating positions

02/21/2022 17:06:07 INFO - Initializing database connection
02/21/2022 17:06:11 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:06:11 INFO - Refreshing units
02/21/2022 17:10:29 INFO - Importing station orders
02/21/2022 17:10:29 INFO - Creating positions

02/21/2022 17:10:38 INFO - Initializing database connection
02/21/2022 17:10:41 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:10:41 INFO - Refreshing units
02/21/2022 17:12:13 INFO - Importing station orders
02/21/2022 17:12:13 INFO - Creating positions

02/21/2022 17:12:38 INFO - Importing station orders
02/21/2022 17:12:38 INFO - Creating positions

02/21/2022 17:13:03 INFO - Importing station orders
02/21/2022 17:13:03 INFO - Creating positions

02/21/2022 17:13:29 INFO - Initializing database connection
02/21/2022 17:13:33 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:13:33 INFO - Refreshing units
02/21/2022 17:13:43 INFO - Importing station orders
02/21/2022 17:13:43 INFO - Creating positions

02/21/2022 17:17:03 INFO - Importing station orders
02/21/2022 17:17:03 INFO - Creating positions

02/21/2022 17:17:13 INFO - Initializing database connection
02/21/2022 17:17:16 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:17:16 INFO - Refreshing units
02/21/2022 17:17:36 INFO - Importing station orders
02/21/2022 17:17:36 INFO - Creating positions

02/21/2022 17:17:50 INFO - Initializing database connection
02/21/2022 17:17:53 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:17:53 INFO - Refreshing units
02/21/2022 17:21:32 INFO - Importing station orders
02/21/2022 17:21:32 INFO - Creating positions

02/21/2022 17:21:38 INFO - Initializing database connection
02/21/2022 17:21:42 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:21:42 INFO - Refreshing units
02/21/2022 17:24:20 INFO - Importing station orders
02/21/2022 17:24:20 INFO - Creating positions

02/21/2022 17:24:26 INFO - Initializing database connection
02/21/2022 17:24:30 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:24:30 INFO - Refreshing units
02/21/2022 17:26:31 INFO - Importing station orders
02/21/2022 17:26:31 INFO - Creating positions

02/21/2022 17:28:34 INFO - Importing station orders
02/21/2022 17:28:34 INFO - Creating positions

02/21/2022 17:29:05 INFO - Importing station orders
02/21/2022 17:29:05 INFO - Creating positions

02/21/2022 17:29:43 INFO - Importing station orders
02/21/2022 17:29:43 INFO - Creating positions

02/21/2022 17:29:49 INFO - Initializing database connection
02/21/2022 17:29:56 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:29:56 INFO - Refreshing units
02/21/2022 17:30:09 INFO - Importing station orders
02/21/2022 17:30:09 INFO - Creating positions

02/21/2022 17:30:14 INFO - Initializing database connection
02/21/2022 17:30:18 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:30:18 INFO - Refreshing units
02/21/2022 17:31:47 INFO - Importing station orders
02/21/2022 17:31:47 INFO - Creating positions

02/21/2022 17:40:06 INFO - Importing station orders
02/21/2022 17:40:06 INFO - Creating positions

02/21/2022 17:40:15 INFO - Importing station orders
02/21/2022 17:40:15 INFO - Creating positions

02/21/2022 17:41:20 INFO - Importing station orders
02/21/2022 17:41:20 INFO - Creating positions

02/21/2022 17:47:24 INFO - Importing station orders
02/21/2022 17:47:24 INFO - Creating positions

02/21/2022 17:47:31 INFO - Importing station orders
02/21/2022 17:47:31 INFO - Creating positions

02/21/2022 17:48:07 INFO - Importing station orders
02/21/2022 17:48:07 INFO - Creating positions

02/21/2022 17:50:12 INFO - Importing station orders
02/21/2022 17:50:12 INFO - Creating positions

02/21/2022 17:50:49 INFO - Initializing database connection
02/21/2022 17:50:56 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:50:56 INFO - Refreshing units
02/21/2022 17:51:33 INFO - Importing station orders
02/21/2022 17:51:33 INFO - Creating positions

02/21/2022 17:51:42 INFO - Initializing database connection
02/21/2022 17:51:46 INFO - Verbose connection successful. Status code: 200
02/21/2022 17:51:46 INFO - Refreshing units
02/22/2022 08:04:01 INFO - Importing station orders
02/22/2022 08:04:01 INFO - Creating positions

02/22/2022 08:04:18 INFO - Importing station orders
02/22/2022 08:04:18 INFO - Creating positions

02/22/2022 08:05:10 INFO - Importing station orders
02/22/2022 08:05:10 INFO - Creating positions

02/22/2022 08:23:57 INFO - Importing station orders
02/22/2022 08:23:57 INFO - Creating positions

02/22/2022 08:24:04 INFO - Initializing database connection
02/22/2022 08:24:04 ERROR - 
Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002BB546C2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BB546C2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\create_api_connection.py", line 15, in create_api_connection
    response = requests.get(url, params=parameters, verify=False)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002BB546C2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
02/22/2022 08:24:04 INFO - Refreshing units
02/22/2022 08:24:04 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\units.py", line 29, in refresh_units
    response = connection.json()
AttributeError: 'NoneType' object has no attribute 'json'
02/22/2022 08:24:08 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\get_recommendations.py", line 28, in get_recommendations
    return recommendations(call_type,grid)
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\recommendations.py", line 104, in recommendations
    for unit in unit_list:
TypeError: 'NoneType' object is not iterable
02/22/2022 08:24:08 INFO - Importing offline units
02/22/2022 08:24:08 INFO - Finished importing offline units
02/22/2022 08:25:15 INFO - Importing station orders
02/22/2022 08:25:15 INFO - Creating positions

02/22/2022 08:25:21 INFO - Initializing database connection
02/22/2022 08:25:21 ERROR - 
Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000182ACCF2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000182ACCF2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\create_api_connection.py", line 15, in create_api_connection
    response = requests.get(url, params=parameters, verify=False)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000182ACCF2E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
02/22/2022 08:25:21 INFO - Refreshing units
02/22/2022 08:25:21 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\units.py", line 29, in refresh_units
    response = connection.json()
AttributeError: 'NoneType' object has no attribute 'json'
02/22/2022 08:25:24 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\get_recommendations.py", line 28, in get_recommendations
    return recommendations(call_type,grid)
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\recommendations.py", line 104, in recommendations
    for unit in unit_list:
TypeError: 'NoneType' object is not iterable
02/22/2022 08:25:24 INFO - Importing offline units
02/22/2022 08:25:24 INFO - Finished importing offline units
02/22/2022 08:25:48 INFO - Importing station orders
02/22/2022 08:25:48 INFO - Creating positions

02/22/2022 08:25:55 INFO - Initializing database connection
02/22/2022 08:25:55 ERROR - 
Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000257A4336D40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000257A4336D40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\create_api_connection.py", line 15, in create_api_connection
    response = requests.get(url, params=parameters, verify=False)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\cgass\AppData\Roaming\Python\Python310\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s0eh943fzf.execute-api.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /prod/api/units/get-public?organizationId=1&jurisdiction=WA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000257A4336D40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
02/22/2022 08:25:55 INFO - Refreshing units
02/22/2022 08:25:55 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\units.py", line 29, in refresh_units
    response = connection.json()
AttributeError: 'NoneType' object has no attribute 'json'
02/22/2022 08:25:59 ERROR - 
Traceback (most recent call last):
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\get_recommendations.py", line 28, in get_recommendations
    return recommendations(call_type,grid)
  File "c:\Users\cgass\OneDrive\Documents\GitHub\CAD-Lite-Recommendations\recommendations.py", line 104, in recommendations
    for unit in unit_list:
TypeError: 'NoneType' object is not iterable
02/22/2022 08:25:59 INFO - Importing offline units
02/22/2022 08:25:59 INFO - Finished importing offline units
02/22/2022 08:27:12 INFO - Importing station orders
02/22/2022 08:27:12 INFO - Creating positions

02/22/2022 08:27:16 INFO - Initializing database connection
02/22/2022 08:27:23 INFO - Verbose connection successful. Status code: 200
02/22/2022 08:27:23 INFO - Refreshing units
02/22/2022 08:28:11 INFO - Importing station orders
02/22/2022 08:28:11 INFO - Creating positions

02/22/2022 08:28:20 INFO - Importing station orders
02/22/2022 08:28:20 INFO - Creating positions

02/22/2022 08:28:59 INFO - Importing station orders
02/22/2022 08:28:59 INFO - Creating positions

02/22/2022 08:29:13 INFO - Importing station orders
02/22/2022 08:29:13 INFO - Creating positions

